server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/saramaraTest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8236

  # Oauth2 Setting
  security:
    oauth2:
      client:
        registration:
          # google login
          google:
            client-id: 709096223722-rj3v1oplgfi2fjnci4p3bqp2aisb85gj.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          # naver login
          naver:
            client-id: GlmvsmwermSEC2qtbcEu
            client-secret: EBgJv_xm9G
            redirect-uri: "{baseUrl}/{action}/oauth2/code+/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  header: Authorization
  #HS512 알고리즘을 사용한다.
  #HS512 알고리즘을 사용하면 Secret Key 는  64(512bit)Byte 이상이 필요하고 base64 로 인코딩해서 사용한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800


logging:
  level:
    com.kakao.saramaracommunity : DEBUG