server:
  port: 80

spring:
  # DB ???? ??
  datasource:
    url: jdbc:mariadb://localhost:3306/saramaraTest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 8236

  jpa:
    hibernate:
      # sql ???? DB? ??
      ddl-auto: update
    properties:
      hibernate:
        # hibernate query format? ??? ??
        format_sql: true
        #hibernate query ? ???? ??
        show_sql: true
    defer-datasource-initialization: true

  # OAuth 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 38f43ff5aee9ea89cc35c4503953906c
            client-secret: EnGcSiLEKbQlwNn9x11BxXZzlsEspMDq
            redirect-uri: http://localhost/login/oauth2/code/kakao
            #redirect-uri: {baseUri}/login/oauth2/kakao/callback/{id}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  header: Authorization
  #HS512 알고리즘을 사용한다.
  #HS512 알고리즘을 사용하면 Secret Key 는  64(512bit)Byte 이상이 필요하고 base64 로 인코딩해서 사용한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800


logging:
  level:
    com.kakao.saramaracommunity : DEBUG